"""changes made to task model

Revision ID: 92347091eed1
Revises: 7159854885dd
Create Date: 2021-12-01 12:52:01.043065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92347091eed1'
down_revision = '7159854885dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.add_column('task', sa.Column('description', sa.String(), nullable=True))
    op.add_column('task', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'title')
    op.drop_column('task', 'description')
    op.drop_column('task', 'completed_at')
    # ### end Alembic commands ###
